In [1]:
import pandas as pd

In [2]:
db = pd.read_csv('datasets/Conditions_Contributing_to_COVID-19_Deaths__by_State_and_Age__Provisional_2020-2021.csv')

In [3]:
db

,Data As Of,Start Date,End Date,Group,Year,Month,State,Condition Group,Condition,ICD10_codes,Age Group,COVID-19 Deaths,Number of Mentions,Flag
0,10/24/2021,01/01/2020,10/23/2021,By Total,NaN,NaN,United States,Respiratory diseases,Influenza and pneumonia,J09-J18,0-24,826.0,867.0,NaN
1,10/24/2021,01/01/2020,10/23/2021,By Total,NaN,NaN,United States,Respiratory diseases,Influenza and pneumonia,J09-J18,25-34,3730.0,3841.0,NaN
2,10/24/2021,01/01/2020,10/23/2021,By Total,NaN,NaN,United States,Respiratory diseases,Influenza and pneumonia,J09-J18,35-44,9797.0,10111.0,NaN
3,10/24/2021,01/01/2020,10/23/2021,By Total,NaN,NaN,United States,Respiratory diseases,Influenza and pneumonia,J09-J18,45-54,25080.0,25916.0,NaN
4,10/24/2021,01/01/2020,10/23/2021,By Total,NaN,NaN,United States,Respiratory diseases,Influenza and pneumonia,J09-J18,55-64,55332.0,57000.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
310495,10/24/2021,06/01/2021,06/30/2021,By Month,2021.0,6.0,Puerto Rico,COVID-19,COVID-19,U071,All Ages,35.0,35.0,NaN
310496,10/24/2021,07/01/2021,07/31/2021,By Month,2021.0,7.0,Puerto Rico,COVID-19,COVID-19,U071,All Ages,29.0,29.0,NaN
310497,10/24/2021,08/01/2021,08/28/2021,By Month,2021.0,8.0,Puerto Rico,COVID-19,COVID-19,U071,All Ages,310.0,310.0,NaN
310498,10/24/2021,09/01/2021,09/30/2021,By Month,2021.0,9.0,Puerto Rico,COVID-19,COVID-19,U071,All Ages,265.0,265.0,NaN
310499,10/24/2021,10/01/2021,10/23/2021,By Month,2021.0,10.0,Puerto Rico,COVID-19,COVID-19,U071,All Ages,37.0,37.0,NaN

# The Atlantic State Wise Data 
Upto March 7 2021 

Source : https://covidtracking.com/data/download

Direct Access : https://covidtracking.com/data/download/all-states-history.csv

In [4]:
!curl -l "https://covidtracking.com/data/download/all-states-history.csv" > data_all_states_atlantic.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2674k  100 2674k    0     0  1496k      0  0:00:01  0:00:01 --:--:-- 1495k

In [5]:
db2 = pd.read_csv("data_all_states_atlantic.csv")

In [8]:
db2["date"].unique()[0]

'2021-03-07'

In [10]:
db2_final_day = db2[db2['date']==db2["date"].unique()[0] ]

In [13]:
db2_final_day

,date,state,death,deathConfirmed,deathIncrease,deathProbable,hospitalized,hospitalizedCumulative,hospitalizedCurrently,hospitalizedIncrease,...,totalTestResults,totalTestResultsIncrease,totalTestsAntibody,totalTestsAntigen,totalTestsPeopleAntibody,totalTestsPeopleAntigen,totalTestsPeopleViral,totalTestsPeopleViralIncrease,totalTestsViral,totalTestsViralIncrease
0,2021-03-07,AK,305.0,NaN,0,NaN,1293.0,1293.0,33.0,0,...,1731628.0,0,NaN,NaN,NaN,NaN,NaN,0,1731628.0,0
1,2021-03-07,AL,10148.0,7963.0,-1,2185.0,45976.0,45976.0,494.0,0,...,2323788.0,2347,NaN,NaN,119757.0,NaN,2323788.0,2347,NaN,0
2,2021-03-07,AR,5319.0,4308.0,22,1011.0,14926.0,14926.0,335.0,11,...,2736442.0,3380,NaN,NaN,NaN,481311.0,NaN,0,2736442.0,3380
3,2021-03-07,AS,0.0,NaN,0,NaN,NaN,NaN,NaN,0,...,2140.0,0,NaN,NaN,NaN,NaN,NaN,0,2140.0,0
4,2021-03-07,AZ,16328.0,14403.0,5,1925.0,57907.0,57907.0,963.0,44,...,7908105.0,45110,580569.0,NaN,444089.0,NaN,3842945.0,14856,7908105.0,45110
5,2021-03-07,CA,54124.0,NaN,258,NaN,NaN,NaN,4291.0,0,...,49646014.0,133186,NaN,NaN,NaN,NaN,NaN,0,49646014.0,133186
6,2021-03-07,CO,5989.0,5251.0,3,735.0,23904.0,23904.0,326.0,18,...,6415123.0,38163,435053.0,NaN,NaN,NaN,2616541.0,6107,NaN,0
7,2021-03-07,CT,7704.0,6327.0,0,1377.0,NaN,NaN,428.0,0,...,6520366.0,0,NaN,396680.0,NaN,NaN,NaN,0,6520366.0,0
8,2021-03-07,DC,1030.0,NaN,0,NaN,NaN,NaN,150.0,0,...,1261363.0,5726,NaN,NaN,NaN,NaN,441942.0,1149,NaN,0
9,2021-03-07,DE,1473.0,1337.0,9,136.0,NaN,NaN,104.0,0,...,1431942.0,5867,NaN,NaN,NaN,NaN,633424.0,1132,NaN,0
10,2021-03-07,FL,32266.0,NaN,66,NaN,82237.0,82237.0,3307.0,92,...,22339182.0,64599,1054711.0,NaN,995580.0,NaN,11248247.0,23190,19482607.0,52132
11,2021-03-07,GA,17906.0,15598.0,1,2308.0,56797.0,56797.0,2008.0,35,...,7359069.0,18827,482568.0,1484921.0,NaN,NaN,NaN,0,7359069.0,18827
12,2021-03-07,GU,133.0,NaN,0,NaN,NaN,NaN,2.0,0,...,120636.0,0,358.0,9299.0,NaN,NaN,NaN,0,120426.0,0
13,2021-03-07,HI,445.0,445.0,1,NaN,2226.0,2226.0,27.0,0,...,1146796.0,5117,NaN,NaN,NaN,NaN,NaN,0,NaN,0
14,2021-03-07,IA,5558.0,NaN,6,NaN,NaN,NaN,167.0,0,...,1326802.0,1556,NaN,1390094.0,113739.0,247999.0,1329195.0,1555,2753899.0,4464
15,2021-03-07,ID,1879.0,1652.0,3,227.0,7184.0,7184.0,150.0,5,...,645838.0,396,NaN,123809.0,NaN,NaN,645838.0,396,1103725.0,877
16,2021-03-07,IL,23014.0,20763.0,12,2251.0,NaN,NaN,1141.0,0,...,18640190.0,68094,NaN,NaN,NaN,NaN,NaN,0,18640190.0,68094
17,2021-03-07,IN,12737.0,12310.0,11,427.0,43217.0,43217.0,656.0,64,...,8242367.0,29427,NaN,NaN,NaN,NaN,3150418.0,5389,8242367.0,29427
18,2021-03-07,KS,4812.0,NaN,0,NaN,9387.0,9387.0,235.0,0,...,1270547.0,0,NaN,602322.0,NaN,NaN,1270547.0,0,2525259.0,0
19,2021-03-07,KY,4819.0,4369.0,13,450.0,19457.0,19457.0,558.0,6,...,3975672.0,0,111886.0,509047.0,NaN,NaN,NaN,0,3975672.0,0
20,2021-03-07,LA,9748.0,9033.0,32,715.0,NaN,NaN,532.0,0,...,5695464.0,21318,NaN,469967.0,NaN,NaN,NaN,0,5634193.0,21098
21,2021-03-07,MA,16417.0,16085.0,43,332.0,19713.0,19713.0,665.0,0,...,16825551.0,96578,NaN,NaN,156185.0,580372.0,4963875.0,9309,16825551.0,96578
22,2021-03-07,MD,7955.0,7773.0,14,182.0,35651.0,35651.0,818.0,79,...,8097590.0,33128,NaN,NaN,198139.0,NaN,3421865.0,2759,8097590.0,33128
23,2021-03-07,ME,706.0,683.0,2,23.0,1570.0,1570.0,67.0,4,...,1660180.0,7490,15113.0,213426.0,NaN,NaN,NaN,0,1660180.0,7490
24,2021-03-07,MI,16658.0,15666.0,0,992.0,NaN,NaN,866.0,0,...,10621967.0,0,537073.0,NaN,NaN,NaN,NaN,0,10621967.0,0
25,2021-03-07,MN,6550.0,6276.0,4,274.0,25978.0,25978.0,224.0,2,...,7111428.0,25369,NaN,451963.0,NaN,NaN,3524061.0,8998,NaN,0
26,2021-03-07,MO,8161.0,NaN,0,NaN,NaN,NaN,955.0,0,...,4565866.0,10659,152126.0,906752.0,135759.0,366813.0,2359226.0,3241,4565866.0,10659
27,2021-03-07,MP,2.0,2.0,0,NaN,4.0,4.0,NaN,0,...,17574.0,1,NaN,NaN,NaN,NaN,17542.0,0,26131.0,0
28,2021-03-07,MS,6808.0,4737.0,3,2071.0,9162.0,9162.0,419.0,0,...,1756955.0,260,81986.0,748339.0,NaN,NaN,NaN,0,1642348.0,0
29,2021-03-07,MT,1381.0,NaN,0,NaN,4630.0,4630.0,63.0,1,...,1104488.0,3132,NaN,NaN,NaN,NaN,NaN,0,1104488.0,3132
30,2021-03-07,NC,11502.0,10169.0,0,1333.0,NaN,NaN,1179.0,0,...,9688838.0,0,NaN,805924.0,NaN,NaN,NaN,0,9688838.0,0
31,2021-03-07,ND,1478.0,NaN,0,NaN,3880.0,3880.0,23.0,2,...,1425146.0,679,NaN,156698.0,NaN,NaN,406303.0,-75,1536487.0,881
32,2021-03-07,NE,2113.0,NaN,0,NaN,6237.0,6237.0,137.0,8,...,2421684.0,1,NaN,NaN,NaN,NaN,974759.0,978,2421684.0,1
33,2021-03-07,NH,1184.0,NaN,3,NaN,1131.0,1131.0,68.0,4,...,1497185.0,15697,39545.0,205103.0,37918.0,NaN,633646.0,521,1497185.0,15697
34,2021-03-07,NJ,23574.0,21177.0,17,2397.0,64396.0,64396.0,1792.0,58,...,10999550.0,2519,NaN,NaN,NaN,NaN,NaN,0,10902830.0,0
35,2021-03-07,NM,3808.0,NaN,12,NaN,13252.0,13252.0,169.0,10,...,2783542.0,11702,NaN,NaN,NaN,NaN,NaN,0,2783542.0,11702
36,2021-03-07,NV,5037.0,NaN,1,NaN,NaN,NaN,399.0,0,...,2770192.0,6201,NaN,NaN,NaN,NaN,1427948.0,2059,NaN,0
37,2021-03-07,NY,39029.0,NaN,59,NaN,NaN,NaN,4789.0,0,...,39695100.0,227768,NaN,NaN,NaN,NaN,NaN,0,NaN,0
38,2021-03-07,OH,17656.0,14752.0,0,2594.0,50881.0,50881.0,820.0,33,...,10257157.0,29289,NaN,1798150.0,NaN,NaN,NaN,0,10257157.0,29289
39,2021-03-07,OK,4534.0,NaN,0,NaN,24332.0,24332.0,346.0,55,...,3575297.0,461,152279.0,NaN,NaN,NaN,NaN,0,3548479.0,0
40,2021-03-07,OR,2296.0,NaN,3,NaN,8714.0,8714.0,158.0,0,...,3850973.0,0,NaN,NaN,NaN,NaN,NaN,0,3850973.0,0
41,2021-03-07,PA,24349.0,NaN,32,NaN,NaN,NaN,1587.0,0,...,10681716.0,52432,NaN,NaN,NaN,NaN,4756664.0,8073,NaN,0
42,2021-03-07,PR,2062.0,1752.0,3,310.0,NaN,NaN,134.0,0,...,407604.0,305,NaN,NaN,NaN,NaN,NaN,0,415664.0,0
43,2021-03-07,RI,2547.0,NaN,0,NaN,9020.0,9020.0,141.0,0,...,3123348.0,13513,NaN,NaN,NaN,NaN,806351.0,1686,NaN,0
44,2021-03-07,SC,8754.0,7744.0,35,1010.0,20725.0,20725.0,579.0,66,...,5183044.0,27264,135125.0,912838.0,NaN,NaN,NaN,0,5107156.0,26282
45,2021-03-07,SD,1900.0,NaN,2,NaN,6705.0,6705.0,72.0,13,...,701924.0,1275,NaN,NaN,NaN,NaN,428129.0,735,701924.0,1275
46,2021-03-07,TN,11543.0,9278.0,0,2265.0,18870.0,18870.0,851.0,0,...,6872745.0,0,NaN,1430665.0,NaN,NaN,NaN,0,6872745.0,0
47,2021-03-07,TX,44451.0,NaN,84,NaN,NaN,NaN,4721.0,0,...,19907384.0,76040,1033285.0,2664340.0,NaN,NaN,NaN,0,19907384.0,76040
48,2021-03-07,UT,1976.0,NaN,1,NaN,14891.0,14891.0,212.0,24,...,2910121.0,6828,NaN,1002177.0,NaN,371319.0,1876802.0,3460,2910121.0,6828
49,2021-03-07,VA,9596.0,8104.0,77,1492.0,24661.0,24661.0,1127.0,24,...,6038209.0,19925,224284.0,1454389.0,NaN,NaN,NaN,0,NaN,0
50,2021-03-07,VI,25.0,25.0,0,NaN,NaN,NaN,NaN,0,...,48881.0,0,NaN,NaN,NaN,NaN,48961.0,0,NaN,0
51,2021-03-07,VT,208.0,NaN,0,NaN,NaN,NaN,31.0,0,...,1124215.0,8748,NaN,NaN,NaN,NaN,335695.0,759,1124215.0,8748
52,2021-03-07,WA,5041.0,NaN,0,NaN,19599.0,19599.0,431.0,43,...,5393756.0,24040,NaN,NaN,NaN,NaN,NaN,0,NaN,0
53,2021-03-07,WI,7106.0,6481.0,4,625.0,26457.0,26457.0,249.0,25,...,7080595.0,19193,NaN,NaN,NaN,NaN,3214557.0,3850,NaN,0
54,2021-03-07,WV,2325.0,1981.0,2,344.0,NaN,NaN,179.0,0,...,2236551.0,6449,33011.0,NaN,NaN,NaN,NaN,0,2236551.0,6449
55,2021-03-07,WY,682.0,NaN,0,NaN,1391.0,1391.0,21.0,0,...,649293.0,0,NaN,NaN,NaN,NaN,228661.0,0,649293.0,0

In [1]:
import pandas as pd

In [4]:
bed = pd.read_csv('beds.csv')

In [5]:
bed.head()

,Abbreviation,State,Hospitals,beds,somethin1,somethin2,somethin3
0,AK,Alaska\t,10,1274,44648,240360,$5953964
1,AL,Alabama\t,90,15102,552677,2720884,$62914457
2,AR,Arkansas\t,52,7964,310634,1372414,$28232928
3,AS,American Samoa\t,1,0,0,0,$0
4,AZ,Arizona\t,77,13744,604065,2725977,$86688062